"""empty message

Revision ID: 5d77e038609d
Revises: 
Create Date: 2020-02-24 15:27:06.809321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d77e038609d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('fullname', sa.String(length=200), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('_UserMixin__hashed_password', sa.String(length=128), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('integration',
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['user.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('setting',
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('fontsize', sa.String(length=5), nullable=True),
    sa.Column('linewidth', sa.Integer(), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_pk'], ['user.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('card',
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('screenshot', sa.LargeBinary(), nullable=True),
    sa.Column('data', sa.PickleType(), nullable=True),
    sa.Column('author_pk', sa.Integer(), nullable=True),
    sa.Column('integration_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_pk'], ['user.pk'], ),
    sa.ForeignKeyConstraint(['integration_pk'], ['integration.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('setting')
    op.drop_table('integration')
    op.drop_table('user')
    # ### end Alembic commands ###
